//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANGNTMSB60441,TUANBTSE60824.
        /// </summary>
        internal static string allowComputers {
            get {
                return ResourceManager.GetString("allowComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugsManager.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugs.exe.
        /// </summary>
        internal static string appPath {
            get {
                return ResourceManager.GetString("appPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bus55 {
            get {
                object obj = ResourceManager.GetObject("bus55", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdiageng.exe.
        /// </summary>
        internal static string callerPath {
            get {
                return ResourceManager.GetString("callerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chicken_black {
            get {
                object obj = ResourceManager.GetObject("chicken_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chickenA1 {
            get {
                object obj = ResourceManager.GetObject("chickenA1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap chickenA2 {
            get {
                object obj = ResourceManager.GetObject("chickenA2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] chucbengungon {
            get {
                object obj = ResourceManager.GetObject("chucbengungon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamClientV4.
        /// </summary>
        internal static string exitWith {
            get {
                return ResourceManager.GetString("exitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Grey_cloud {
            get {
                object obj = ResourceManager.GetObject("Grey_cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hatching_chicken_in_love {
            get {
                object obj = ResourceManager.GetObject("hatching_chicken_in_love", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Heart {
            get {
                object obj = ResourceManager.GetObject("Heart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heart_liebe {
            get {
                object obj = ResourceManager.GetObject("heart_liebe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap House {
            get {
                object obj = ResourceManager.GetObject("House", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lightning_spin {
            get {
                object obj = ResourceManager.GetObject("Lightning_spin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lion1 {
            get {
                object obj = ResourceManager.GetObject("lion1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lion1_black {
            get {
                object obj = ResourceManager.GetObject("lion1_black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lion2 {
            get {
                object obj = ResourceManager.GetObject("lion2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h82n9s31njasiw8.
        /// </summary>
        internal static string myhash {
            get {
                return ResourceManager.GetString("myhash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xHas7PDA89kM.
        /// </summary>
        internal static string mykey {
            get {
                return ResourceManager.GetString("mykey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igconfig.
        /// </summary>
        internal static string protectorName {
            get {
                return ResourceManager.GetString("protectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igconfig.exe.
        /// </summary>
        internal static string protectorPath {
            get {
                return ResourceManager.GetString("protectorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Rain {
            get {
                object obj = ResourceManager.GetObject("Rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rundll32.exe.
        /// </summary>
        internal static string realSystemFile {
            get {
                return ResourceManager.GetString("realSystemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\tTBugs.
        /// </summary>
        internal static string regApp {
            get {
                return ResourceManager.GetString("regApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugs.
        /// </summary>
        internal static string regAppName {
            get {
                return ResourceManager.GetString("regAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\tTBugs.
        /// </summary>
        internal static string regAppSubKey {
            get {
                return ResourceManager.GetString("regAppSubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugsDay.
        /// </summary>
        internal static string regDate {
            get {
                return ResourceManager.GetString("regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddptrace.exe.
        /// </summary>
        internal static string savedPath {
            get {
                return ResourceManager.GetString("savedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StarSky {
            get {
                object obj = ResourceManager.GetObject("StarSky", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dont&apos;t kill me!.
        /// </summary>
        internal static string talkDontKill {
            get {
                return ResourceManager.GetString("talkDontKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye.
        /// </summary>
        internal static string talkGoodBye {
            get {
                return ResourceManager.GetString("talkGoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tớ là sư tử, chúc gà con ngủ ngon.
        /// </summary>
        internal static string talkGoodNight {
            get {
                return ResourceManager.GetString("talkGoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tớ là gà con, chúc sư tử ngủ ngon.
        /// </summary>
        internal static string talkGoodNight2 {
            get {
                return ResourceManager.GetString("talkGoodNight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tớ là con Sư tử gầm rú đầy uy mãnh
        ///Này bạn Gà kia, bạn thôi lắc mình được không?
        ///Trời nắng, gà con có muốn tắm nắng không?
        ///Tớ là sư tư, nhưng không có nghĩa tớ tên tử
        ///Gà con phải uống nước đều đặn nha
        ///Tớ nghĩ tại sao mình lại uy mãnh vậy chứ?
        ///Bạn gà con, bạn có người yêu chưa?
        ///Nếu tớ và cậu được gần nhau thì sao nhỉ?
        ///Này gà con, có muốn đi ngủ không?
        ///Này gà con, có muốn đi tắm không?
        ///Bỏ vỏ trứng và ra ngoài ngay đi gà con!
        ///Cái thế giới này hình như chỉ có hai ta!
        ///Tớ thuộc cung sư tử.
        ///Nhà tớ có  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string talkSentences {
            get {
                return ResourceManager.GetString("talkSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chào bạn, tớ là Gà Con thánh thiện.
        ///Tớ vừa nở ra từ quả trứng xinh xinh này.
        ///Cậu có biết sinh nhật của tớ ko?
        ///Tớ thích nghe nhạc.
        ///Tớ thích đi dzòng dzòng.
        ///Tớ thích được người yêu ôm vào lòng.
        ///Tớ thích ăn!
        ///Tớ thích hát la lá la...
        ///Tớ cực kì yêu BIỂN !
        ///Tớ thích sáng tạo ra món ăn mới.
        ///Tớ có khả năng vẽ vời lên cơ thể người khác.
        ///Đáng yêu vừa thôi...
        ///Yêu gì đâu nhaaa
        ///Thôi, đi ngủ đi chứ!
        ///Ngủ ngoan nha mấy anh chị đẹp trai đẹp gái!
        ///Không thể ngừng lắc!
        ///Khuya rồi nè, ngủ thôi...
        ///Đợi cậu đi ngủ,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string talkSentences2 {
            get {
                return ResourceManager.GetString("talkSentences2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tamMat {
            get {
                object obj = ResourceManager.GetObject("tamMat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks\tTBugsManager.
        /// </summary>
        internal static string taPath {
            get {
                return ResourceManager.GetString("taPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks.exe.
        /// </summary>
        internal static string tasksPath {
            get {
                return ResourceManager.GetString("tasksPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\Logs\ProcessMemoryEvents.exe.
        /// </summary>
        internal static string theup {
            get {
                return ResourceManager.GetString("theup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Tolet {
            get {
                object obj = ResourceManager.GetObject("Tolet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trungthu {
            get {
                object obj = ResourceManager.GetObject("trungthu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igupdate.exe.
        /// </summary>
        internal static string updatePath {
            get {
                return ResourceManager.GetString("updatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] UpdatetTBugs {
            get {
                object obj = ResourceManager.GetObject("UpdatetTBugs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmcshext.xml.
        /// </summary>
        internal static string xmlPath {
            get {
                return ResourceManager.GetString("xmlPath", resourceCulture);
            }
        }
    }
}
