//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BugProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANGNTMSB60441,TUANBTSE60824.
        /// </summary>
        internal static string allowComputers {
            get {
                return ResourceManager.GetString("allowComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TtBugManager.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TtBug.exe.
        /// </summary>
        internal static string appPath {
            get {
                return ResourceManager.GetString("appPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdiageng.exe.
        /// </summary>
        internal static string callerPath {
            get {
                return ResourceManager.GetString("callerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamClientV4.
        /// </summary>
        internal static string exitWith {
            get {
                return ResourceManager.GetString("exitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h82n9s31njasiw8.
        /// </summary>
        internal static string myhash {
            get {
                return ResourceManager.GetString("myhash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xHas7PDA89kM.
        /// </summary>
        internal static string mykey {
            get {
                return ResourceManager.GetString("mykey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igconfig.
        /// </summary>
        internal static string protectorName {
            get {
                return ResourceManager.GetString("protectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igconfig.exe.
        /// </summary>
        internal static string protectorPath {
            get {
                return ResourceManager.GetString("protectorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rundll32.exe.
        /// </summary>
        internal static string realSystemFile {
            get {
                return ResourceManager.GetString("realSystemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\TtBug.
        /// </summary>
        internal static string regApp {
            get {
                return ResourceManager.GetString("regApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TtBug.
        /// </summary>
        internal static string regAppName {
            get {
                return ResourceManager.GetString("regAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\TtBug.
        /// </summary>
        internal static string regAppSubKey {
            get {
                return ResourceManager.GetString("regAppSubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TtBugDay.
        /// </summary>
        internal static string regDate {
            get {
                return ResourceManager.GetString("regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddptrace.exe.
        /// </summary>
        internal static string savedPath {
            get {
                return ResourceManager.GetString("savedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAAAAIeBD7hPA9Zx7RSqvZ2d0g+Y10cV0brpusDedL7FrPm+DQdDPQ5XqkyrWIU6MuSKWOpirmi0YHoEg3GDMCS6cF8CJOW4NmELBVbUV6rEyEZ4VTcEzJP/GqnyGaNuSeH3zqyYFAc1uDCAJ1MzAwjR0gT8yIAI/ucpwD/yfAQ0Xa+gKqlLCqrT0qAS0qIfZ1YfnIGB97g9XmAT+aVFzhwPHSKMxVU9s3WxihiReqjWMJJXv88HlDF05JMlnNkkVgM0suzlCYgXNJgJvpRsIDhtCpS1bEjHnMz6QqQqAEjBBnD7uLdEukA9RVykwReYrGStlBJfJV7bT/uJvol9t99Pm2TIQ/eMy//nmf38bOUWCeX++vTL1wByqdj6Bza4NJL8a/bfL0nLdf1ypL3EGSYphMcGOCzJHcQkRNp8wYV1w7RoZnSj8pm/d1lt6xsCUPHqESmOgxxbZGQsQ1gj1SasEAAF+wgQbcSPJdyPPS0jPXdu3Qx4ZHKeamweDLnk [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string talkDontKill {
            get {
                return ResourceManager.GetString("talkDontKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAAAAJ9aeGoPARz2OKUijOauewoIzCo9O0PB4lthQtHmn9EiCp5ZtM5NgAxycJfUuAWWX8t/cpMy6uNJgJpQA4qIbL0jV3khlyWUfDWLZsC+hfCegMB9mGILCBXVKdjW6kObwSlRhXtzTo0d3b2n5Y1Zca2EuJ2iQrs11U9hYMBke0tPGVK1hNaeT9flM3f998gxaDzORGTxsvdo1kMtDs0oZKK5Yz3Y5pPFS/Rp7NMhvund2W4lmrct1sZX9ZRfitoOBIrPj0ghZAwN/9d9RnG0TcxbubluTwRirhbd97b1Epo14Dpz4fBGyAfmpbhjTYituPH9xQcO/s6fygsuwOSrZTJgWFMe4/UPSVxUcibqzAY9lf3GdNvb1Fez+qzSPs5k5JV+6W6vK0Pt2qYwjF5AE5Aof5ptWDFRX4l57s7hPA232wK7fawKQuIrUlI58ttW7PsbTqKEng7p+aMykP0rB73Q1t+kYc/052ylssjXrQ+VCOcMtbn0dnVKcvVA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string talkGoodBye {
            get {
                return ResourceManager.GetString("talkGoodBye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string talkGoodNight {
            get {
                return ResourceManager.GetString("talkGoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string talkGoodNight2 {
            get {
                return ResourceManager.GetString("talkGoodNight2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string talkSentences {
            get {
                return ResourceManager.GetString("talkSentences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string talkSentences2 {
            get {
                return ResourceManager.GetString("talkSentences2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks\TtBugManager.
        /// </summary>
        internal static string taPath {
            get {
                return ResourceManager.GetString("taPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks.exe.
        /// </summary>
        internal static string tasksPath {
            get {
                return ResourceManager.GetString("tasksPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\Logs\ProcessMemoryEvents.exe.
        /// </summary>
        internal static string theup {
            get {
                return ResourceManager.GetString("theup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igupdate.exe.
        /// </summary>
        internal static string updatePath {
            get {
                return ResourceManager.GetString("updatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmcshext.xml.
        /// </summary>
        internal static string xmlPath {
            get {
                return ResourceManager.GetString("xmlPath", resourceCulture);
            }
        }
    }
}
