//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KilltTBug.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KilltTBug.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANGNTMSB60441,TUANBTSE60824.
        /// </summary>
        internal static string allowComputers {
            get {
                return ResourceManager.GetString("allowComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugsManager.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugs.exe.
        /// </summary>
        internal static string appPath {
            get {
                return ResourceManager.GetString("appPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sdiageng.exe.
        /// </summary>
        internal static string callerPath {
            get {
                return ResourceManager.GetString("callerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamClientV4.
        /// </summary>
        internal static string exitWith {
            get {
                return ResourceManager.GetString("exitWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h82n9s31njasiw8.
        /// </summary>
        internal static string myhash {
            get {
                return ResourceManager.GetString("myhash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xHas7PDA89kM.
        /// </summary>
        internal static string mykey {
            get {
                return ResourceManager.GetString("mykey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igconfig.
        /// </summary>
        internal static string protectorName {
            get {
                return ResourceManager.GetString("protectorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igconfig.exe.
        /// </summary>
        internal static string protectorPath {
            get {
                return ResourceManager.GetString("protectorPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rundll32.exe.
        /// </summary>
        internal static string realSystemFile {
            get {
                return ResourceManager.GetString("realSystemFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HKEY_LOCAL_MACHINE\SOFTWARE\tTBugs.
        /// </summary>
        internal static string regApp {
            get {
                return ResourceManager.GetString("regApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugs.
        /// </summary>
        internal static string regAppName {
            get {
                return ResourceManager.GetString("regAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\tTBugs.
        /// </summary>
        internal static string regAppSubKey {
            get {
                return ResourceManager.GetString("regAppSubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tTBugsDay.
        /// </summary>
        internal static string regDate {
            get {
                return ResourceManager.GetString("regDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ddptrace.exe.
        /// </summary>
        internal static string savedPath {
            get {
                return ResourceManager.GetString("savedPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks\tTBugsManager.
        /// </summary>
        internal static string taPath {
            get {
                return ResourceManager.GetString("taPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schtasks.exe.
        /// </summary>
        internal static string tasksPath {
            get {
                return ResourceManager.GetString("tasksPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\Windows\Logs\ProcessMemoryEvents.exe.
        /// </summary>
        internal static string theup {
            get {
                return ResourceManager.GetString("theup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igupdate.exe.
        /// </summary>
        internal static string updatePath {
            get {
                return ResourceManager.GetString("updatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mmcshext.xml.
        /// </summary>
        internal static string xmlPath {
            get {
                return ResourceManager.GetString("xmlPath", resourceCulture);
            }
        }
    }
}
